# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  application:
    build:
      context: "C:\\Users\\denis\\OneDrive\\Рабочий стол\\eco-monitoring\\eco__monitoring"
      dockerfile: "server/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/server.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "application:dev"
    ports: []
    volumes:
    - "C:\\Users\\denis\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\denis\\OneDrive\\Рабочий стол\\eco-monitoring\\eco__monitoring\\\
      server:/app:rw"
    - "C:\\Users\\denis\\OneDrive\\Рабочий стол\\eco-monitoring\\eco__monitoring:/src:rw"
    working_dir: "/app"
