version: '3.4'

networks:
  deploy-guide:
    driver: bridge

services:
  postgres.database:
    image: postgres:latest
    container_name: postgres.database
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - deploy-guide
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - pgadmin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - deploy-guide
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  
  application:
    image: application
    container_name: application
    restart: always
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - deploy-guide
    depends_on:
      - postgres.database
      - pgadmin
    command: [ "dotnet", "ef", "database update" ]

volumes:
  postgres-data: