version: '3.4'

networks:
  deploy-guide:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - deploy-guide
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /path/to/local/data:/var/lib/postgresql/data
      - /path/to/local/postgresql.conf:/etc/postgresql/postgresql.conf
  
  application:
    image: application
    container_name: application
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - deploy-guide
    depends_on:
      - postgres
    command: [ "dotnet", "ef", "database update" ]
    
volumes:
  postgres-data:
      