version: '3.4'

networks:
  deploy-guide:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - deploy-guide
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: eco-monitoring
    volumes:
      - /path/to/local/data:/var/lib/postgresql/data
      - /path/to/local/postgresql.conf:/etc/postgresql/postgresql.conf
  
  application:
    image: application
    container_name: application
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - deploy-guide
    depends_on:
      - postgres
    command: [ "dotnet", "ef", "database update" ]
    
volumes:
  postgres-data:
      